spring:
  profiles:
    active: base

logging:
  level:
    root: debug

micro-application:
  application-demo:
    application-name: 企业综合管理插件
    application-type: application
    application-tag: enterprise-comprehensive
    menus:
      - menu-tag: enterprise-comprehensive
        plugin-id: micro-app-enterprise
        zh-cn: 企业插件
        en: Enterprise Comprehensive Management Plugin
        layout: left
        menu-type: M
        icon: Monitor
        path: /enterprise-comprehensive
        operates:
          - operate-tag: view
            zh-cn: 查看
            en: View
        menus:
          - menu-tag: message-release
            plugin-id: micro-app-enterprise
            zh-cn: 消息发布
            en: Message Release
            layout: left
            menu-type: C
            path: /enterprise-comprehensive/message-release
            operates:
              - operate-tag: view
                zh-cn: 查看
                en: View
              - operate-tag: edit
                zh-cn: 编辑
                en: Edit
          - menu-tag: knowledge-base
            plugin-id: micro-app-enterprise
            zh-cn: 企业知识库
            en: Enterprise Knowledge Base
            layout: left
            menu-type: C
            path: /enterprise-comprehensive/knowledge-base
            operates:
              - operate-tag: view
                zh-cn: 查看
                en: View
              - operate-tag: edit
                zh-cn: 编辑
                en: Edit
          - menu-tag: material-manage
            plugin-id: micro-app-enterprise
            zh-cn: 企业流程
            en: Business Process
            layout: left
            menu-type: C
            path: /enterprise-comprehensive/business-process
            operates:
              - operate-tag: view
                zh-cn: 查看
                en: View
              - operate-tag: edit
                zh-cn: 编辑
                en: Edit



